### ISSUE TITLE
Bug: preview does not open and there is an error in Neovim

### ISSUE THREAD

**Issue by refaelsh** [tigion/nvim-asciidoc-preview#2]
Here is what happens when I try to run `:AsciiDocPreview`:

![2023-04-25_14-01](https://user-images.githubusercontent.com/2750775/234257681-16779b42-cd58-4495-b116-9c76548c94dd.png)

Looks like a bug.
I am using the latest Neovim on NixOS.

Thanks in advance.

**Comment by tigion** [comment]
Thanks for the feedback. I'll take a look at it.

**Comment by tigion** [comment]
I think it is an error in the path name between Unix/Linux and Windows. (`/` vs `\`)

**Comment by tigion** [comment]
Does the error still exist in the current version of the plugin?

**Comment by refaelsh** [comment]
I just tried now again with latest version and it works. Thank you very much for not forgetting this issue :-)
