### ISSUE TITLE
Bug: Created Diagram (mermaid) does not update

### ISSUE THREAD

**Issue by cloud-wanderer** [tigion/nvim-asciidoc-preview#5]
**Issue:**

If you have a diagram, in my case mermaid, that you'd like to preview, it only renders it once. Any updates are not reflected in the rendered graph.

**What i tried:**

I tried changing the browser, changing the server converter from js to cmd and other similar things, like disabling the browser cache. None worked.

**System:**
* MacOS with M1 / ARM
* Neovim 0.10
* Node 22.2.0
* Asciidoctor 2.0.23 [https://asciidoctor.org] Runtime Environment (ruby 3.3.2 (2024-05-30 revision e5a195edf6) [arm64-darwin22]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
* Browser: LibreWolf, Waterfox, Firefox, Chrome latest versions

**Steps to reproduce**

Use an example document like the following, preview it, then make changes to the graph. You will see that the text version updates, but not the rendered graph.

```adoc
= Diagram Mermaid Sample

.Mermaid graph
[source,zsh]
----
graph TD
A[Christmas] -->|Get money| B(Go shopping)
B --> C{Let me think}
C -->|One| D[Laptop]
C -->|Two| E[iPhone]
C -->|Three| F[Car]
D --> E
D --> E
----
```

**Comment by tigion** [comment]
Hm ... I can't reproduce the error. If I use your example in an Asciidoctor file like this ([Diagram Blocks](https://docs.asciidoctor.org/diagram-extension/latest/blocks/)):

```adoc
.Mermaid graph
[mermaid]
// [mermaid, "example-mermaid", svg]
....
graph TD
A[Christmas] -->|Get money| B(Go shopping)
B --> C{Let me think}
C -->|One| D[Laptop]
C -->|Two| E[iPhone]
C -->|Three| F[Car]
D --> E
D --> E
....
```

It is displayed correctly and after a change and saving, the change is also displayed correctly in the preview.

How is the diagram integrated in the Asciidoctor file?

> [!NOTE]
> The preview is updated every time the AsciiDoc file is saved.

**Comment by cloud-wanderer** [comment]
![bug](https://github.com/tigion/nvim-asciidoc-preview/assets/58083094/9d0d37a0-980d-49e6-a478-bb47a864d0e0)

This is indeed a bit. I tried to showcase it in the attached recording. On the bottom you see chrome, on the right is Firefox.

You can see me editing, saving then it updates - but only the text.

Chrome is a fresh install, no changes.

**Comment by tigion** [comment]
Please send me your AsciiDoc file (content as a code block or file as an attachment) so that I can test it with your exact example.

**Comment by cloud-wanderer** [comment]
Sure, it's just a test file.

I believe it's a not the code itself that causes it, but rather a cashing issue. It seems the SVG's are stored and just reused for some reason, as even a server restart does not change anything. It's honestly a bit puzzling. I checked the generated svg and the content does not change:

`= Diagram Mermaid
:tags: asciidoc mermaid graphs

== How to use mermaid

.Mermaid graph
[source,zsh]
----
graph TD
A[Christmas] -->|Get money| B(Go shopping)
B --> C{Let me show it}
C -->|One| D[Test]
C -->|Two| E[iPhone 3]
C -->|Three| F[Car]
D --> E
D --> E
----

[mermaid,format=svg, svg-type=inline]
----
graph TD
A[Christmas] -->|Get money| B(Go shopping)
B --> C{Let me think}
C -->|One| D[Laptop]
C -->|Two| E[iPhone]
C -->|Three| F[Car]
D --> E
D --> E
----

.Mermaid Sequence Diagram
[source,zsh]
----
sequenceDiagram
A--> B: Query
B->> C: Forward query
Note right of C: Thinking...
C->> B: Response
B->> A: Forward response
----

[mermaid,target=mermaid-sample, format=svg, svg-type=inline]
....
sequenceDiagram
A--> B: Query
B->> C: Forward query
Note right of C: Thinking...
C->> B: Response
B->> A: Forward response
.... 


`

**Comment by cloud-wanderer** [comment]
Closed by author, as reason could not be found, but was **solved after reinstalling all dependencies on Mac via _brew_**
