### ISSUE TITLE
Cannot get the plugin to work (Despite positive checkhealth) NixOS 24.05 (flake included to test)

### ISSUE THREAD

**Issue by jirafey** [tigion/nvim-asciidoc-preview#7]
`:checkhealth asciidoc-preview`

==============================================================================
asciidoc-preview: require("asciidoc-preview.health").check()

nvim-asciidoc-preview ~
- OK macOS (Linux) supported
- OK node installed
- OK npm installed
- OK curl installed

Asciidoctor (optional) ~
- The following warnings or errors can be ignored
  if Asciidoctor.js (`converter = 'js'`) is used.
- WARNING asciidoctor not installed
- OK ruby installed
- WARNING asciidoctor gem not installed
- WARNING asciidoctor-diagram gem not installed

(I cannot find the file ` ~/.local/state/nvim/nvim-asciidoc-preview-server.log`)

![image](https://github.com/user-attachments/assets/8db94bc4-4e3d-4ce1-9771-874be942b53b)

Flake for tests:
REQUIRED: 
- nix

With flakes enabled
`nix run github:jirafey/nvim-flake`

if you have `git cloned the repo` -> `cd to the repo` and  `nix run`

Legacy (may seem like it stalls)
`nix-shell -p '(import (builtins.fetchTarball "https://github.com/jirafey/nvim-flake/archive/master.tar.gz")).packages.${builtins.currentSystem}.default' --run nvim`

If you need the link: https://github.com/jirafey/nvim-flake
Nvim version:

![image](https://github.com/user-attachments/assets/d92cc412-82a5-45f8-a4bb-231e2094a91d)

**Comment by jirafey** [comment]
@EdenEast maybe you can help here since I see you're inactive here for quite some time but you seem to use NixOS

**Comment by jirafey** [comment]
was able to do this, thanks to  @Gerg-L 

nix run . -- basic-example.adoc 
![image](https://github.com/user-attachments/assets/7cfd368a-b136-43f2-8350-7f51a94f98f1)

however `:AsciiDocPreview` `:AsciiDocPreviewOpen` does not work

`:AsciiDocPreview` just doesn't throw and error but just does nothing

**Comment by jirafey** [comment]
https://github.com/user-attachments/assets/b90f3dd4-524a-4444-b298-6de55d945ea9

**Comment by tigion** [comment]
Okay, I'll take a look

**Comment by tigion** [comment]
It seems as if the preview server cannot be started, which is why the page cannot be reached in the web browser and no log file can be written.

Does the directory `~/.local/state/nvim/` exist?
The plugin may have problems finding the correct paths in your environment.

**Comment by tigion** [comment]
Can you please show me the following results?

Open an AsciiDoc file in nvim and execute the following commands:

- `lua print(vim.g.tigion_asciidocPreview_rootDir)` (this shows the plugin path)
- `lua print(vim.fn.stdpath('log'))` (this shows the log and cache path of nvim)
- `lua print(vim.fn.stdpath('cache'))`

Open the Preview with `:AsciidocPreview`, wait for the webbrowser and run the following command in the terminal:
- `ps -ax | grep -v grep | grep nvim-asciidoc-preview` (this shows, if the preview server is running)

> [!WARNING]
> Attention, the user name is displayed. So perhaps anonymize this information first.

**Comment by jirafey** [comment]
> It seems as if the preview server cannot be started, which is why the page cannot be reached in the web browser and no log file can be written.
> 
> Does the directory `~/.local/state/nvim/` exist? The plugin may have problems finding the correct paths in your environment.

I did not have ~/.local/state/nvim/ before but I installed `kickstart-nix.nvim` so it probably created that.
I will try using the flake i was using before then. I'll try to provide that later this day.

**Comment by jirafey** [comment]
> Can you please show me the following results?
> 
> Open an AsciiDoc file in nvim and execute the following commands:
> 
>     * `lua print(vim.g.tigion_asciidocPreview_rootDir)` (this shows the plugin path)
> Output: `/nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source`

>     * `lua print(vim.fn.stdpath('log'))` (this shows the log and cache path of nvim)
> Output: `/home/user/.local/state/gerg` 

>     * `lua print(vim.fn.stdpath('cache'))`
> Output: `/home/user/.local/state/gerg`
> 
> Open the Preview with `:AsciidocPreview`, wait for the webbrowser and run the following command in the terminal:
> `E492: Not an editor command: AsciidocPreview` 
>     * `ps -ax | grep -v grep | grep nvim-asciidoc-preview` (this shows, if the preview server is running)
> 
![image](https://github.com/user-attachments/assets/08090184-73fc-4739-8275-93d3710228d4)



> 
> Warning
> 
> Attention, the user name is displayed. So perhaps anonymize this information first.

if this is confusing keep in mind this:

- username = user
- hostname = hostname

**Comment by tigion** [comment]
The command is `:AsciiDocPreview` sorry for the typo.

**Comment by jirafey** [comment]
> The command is `:AsciiDocPreview` sorry for the typo.

The `:AsciiDocPreview`, `:AsciiDocPreviewNotify`, `:AsciiDocPreviewOpen`, `:AsciiDocPreviewStop` output nothing, just sit there seems to lag nvim a bit and i need to click `ESC` a few times, or wait, ive made a bash script with your proposed `ps -ax | grep -v grep | grep nvim-asciidoc-preview`
so it watches it every 0.1s but no command resulted in any output rather than the expected no results, this may be due to my lack of knowledge of NixOS, grep, ps, and anything in between so your command may work on any linux but not on NixOS.

the shebang is unique for NixOS, the output was just "Not running."
```bash
#!/usr/bin/env bash
while true; do
  ps -ax | grep -v grep | grep nvim-asciidoc-preview > /dev/null && echo "Running..." || echo "Not running."
  sleep 0.1 # Check every 0.1 seconds
done
```

**Comment by tigion** [comment]
The server for the preview is not started, therefore the commands do not work and no log file is written. I am not yet sure what the problem is.

Can you try the following:

1. `cd /nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source` (I hope this is the correct path to the plugin)
2. `server/scripts/start.sh --port 11235` (starts the preview server)
3. open `http://localhost:11235/` in the web browser and check if an output is coming
4. `curl -s -X POST http://localhost:11235/api/actions/stop` (stops the preview server)

Does the file *server/logs/nvim-asciidoc-preview-server.log* in */nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source* exist?

What is the content of the log file?

**Comment by jirafey** [comment]
> The server for the preview is not started, therefore the commands do not work and no log file is written. I am not yet sure what the problem is.
> 
> Can you try the following:
> 
>     1. `cd /nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source` (I hope this is the correct path to the plugin)
> 
>     2. `server/scripts/start.sh --port 11235` (starts the preview server)
> 
>     3. open `http://localhost:11235/` in the web browser and check if an output is coming
> 
>     4. `curl -s -X POST http://localhost:11235/api/actions/stop` (stops the preview server)
> 
> 
> Does the file _server/logs/nvim-asciidoc-preview-server.log_ in _/nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source_ exist?
> 
> What is the content of the log file?

I'll try to get someone that is more informed in NixOS to help me with this: for your information here is the content of your commands

```sh
$ cd /nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source

[user@hostname:/nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source]$ server/scripts/start.sh --port 11235
Log directory '' does not exist. Use default: 'logs/'
mkdir: cannot create directory ‘logs’: Read-only file system
server/scripts/start.sh: line 38: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 21: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 40: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 21: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 21: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 21: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 21: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 21: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 71: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 21: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 73: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 74: logs/nvim-asciidoc-preview-server.log: No such file or directory

[user@hostname:/nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source]$ sudo server/scripts/start.sh --port 11235
[sudo] password for user: 
Log directory '' does not exist. Use default: 'logs/'
mkdir: cannot create directory ‘logs’: Read-only file system
server/scripts/start.sh: line 38: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 21: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 40: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 21: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 21: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 21: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 21: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 21: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 71: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 21: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 73: logs/nvim-asciidoc-preview-server.log: No such file or directory
server/scripts/start.sh: line 74: logs/nvim-asciidoc-preview-server.log: No such file or directory

[user@hostname:/nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source]$ ls
LICENSE  lua  plugin  README.md  server

[user@hostname:/nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source]$ pwd
/nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source
```

**Comment by NobbZ** [comment]
Please be aware that the last quoted sentence refers to the log file used during the bash script, not to the server as a whole.

**Comment by tigion** [comment]
Okay, the steps were used to start the server manually for testing with a fallback log directory to this directory. Since it is a Read-only file system, the log file cannot be written.

Normally it would write the logfile from the plugin to `lua print(vim.fn.stdpath('log'))`. 

The path to the log file can be specified with `--logdir /path/to/logdir/` to a writable directory.

- `server/scripts/start.sh --port 11235 --logdir /path/to/logdir/`

I think in NixOS there is a special handling needed.

**Comment by NobbZ** [comment]
I found some time to experiment on my own.

```text
--------------------------------------------------------
2024-08-07 21:23:50 [INFO]: Starting script...
--------------------------------------------------------
2024-08-07 21:23:50 [INFO]: Log file: /home/nobbz/.local/state/gerg/nvim-asciidoc-preview-server.log
2024-08-07 21:23:50 [OKAY]: 'npm' found
2024-08-07 21:23:50 [OKAY]: 'node' found
2024-08-07 21:23:50 [OKAY]: '/nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source/server/server.js' found
2024-08-07 21:23:51 [INFO]: Arguments: --logdir /home/nobbz/.local/state/gerg --cachedir /home/nobbz/.cache/gerg --port 11235
--------------------------------------------------------
2024-08-07 21:23:51 [INFO]: Starting node server...
--------------------------------------------------------
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source/server/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source/server/server.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/8hnhmgimylvbfxlrvxalkn0qf4y82hqr-source/server/server.js'
  ]
}

Node.js v20.14.0
```

This is basically what I expected, required dependencies are not available to start the server. I am sadly not sure how to tackle that. I am not using neovim for long enough myself to know all the edges of the ecosystem within nixpkgs. Also I know that this particular config uses non-standard build helpers, which are quite young.

I think a good start would be, if there was a message issued by the plugin that the server couldn't be started.

To fix the underlying problem for this particular configuration, I think only @gerg-l can help, noone else really knows their tooling well enough ;)

**Comment by Gerg-L** [comment]
I think the node part of this plugin needs to be properly packaged

**Comment by tigion** [comment]
If the plugin directory is not writable, the required packages cannot be installed. These are then missing for starting.
The installation is initiated via the Lazy.nvim Config of the plugin.

I will add a check to the plugin or the `:checkhealth`.

**Comment by tigion** [comment]
I have pushed a new version. Now an error message is displayed if the plugin directory is not writable.

**Comment by Gerg-L** [comment]
I've gotten it to work
```nix
pkgs.buildNpmPackage {
            name = "nvim-asciidoc";
            src = pkgs.fetchFromGitHub {
              owner = "tigion";
              repo = "nvim-asciidoc-preview";
              rev = "06b13166ec0aaa5ae59531bc5c38017171323947";
              hash = "sha256-6v5DsgCDbpAOHFaNk1i/j5KzO0NFCkIwDpT0Dezceao=";
            };
            postPatch = "pushd server";
            npmDepsHash = "sha256-HGEuBpMkupoLMkqrNo1tw989dVzrIiZf5OJCMo4FOgU=";
            dontNpmBuild = true;
            installPhase = ''
              runHook preInstall

              popd
              cp -r . $out/

              runHook postInstall
            '';
          };
          ```

**Comment by jirafey** [comment]
> I've gotten it to work
> 
> ```nix
> pkgs.buildNpmPackage {
>   name = "nvim-asciidoc";
>   src = pkgs.fetchFromGitHub {
>     owner = "tigion";
>     repo = "nvim-asciidoc-preview";
>     rev = "06b13166ec0aaa5ae59531bc5c38017171323947";
>     hash = "sha256-6v5DsgCDbpAOHFaNk1i/j5KzO0NFCkIwDpT0Dezceao=";
>   };
>   postPatch = ''
>     pushd server
>   '';
>   npmDepsHash = "sha256-HGEuBpMkupoLMkqrNo1tw989dVzrIiZf5OJCMo4FOgU=";
>   dontNpmBuild = true;
>   installPhase = ''
>     runHook preInstall
> 
>     popd
>     cp -r . $out/
> 
>     runHook postInstall
>   '';
> }
> ```

how can I apply this change?

**Comment by Gerg-L** [comment]
Use that snippet instead of adding the plugin from npins, i can help you elsewhere, this can probably get closed

**Comment by jirafey** [comment]
with this change:
https://github.com/jirafey/nvim-flake/blob/3a6501e0e97039826e4dbad56a71a985929b364d/flake.nix#L113
```nix
plugins =
              [
                (pkgs.buildNpmPackage {
                  name = "nvim-asciidoc";
                  src = pkgs.fetchFromGitHub {
                  owner = "tigion";
                  repo = "nvim-asciidoc-preview";
                  rev = "06b13166ec0aaa5ae59531bc5c38017171323947";
                  hash = "sha256-6v5DsgCDbpAOHFaNk1i/j5KzO0NFCkIwDpT0Dezceao=";
                  };
                  postPatch = ''
                    pushd server
                  '';
                  npmDepsHash = "sha256-HGEuBpMkupoLMkqrNo1tw989dVzrIiZf5OJCMo4FOgU=";
                  dontNpmBuild = true;
                  installPhase = ''
                    runHook preInstall
                    popd
                    cp -r . $out/
                  runHook postInstall
                  '';
                })
                ```
                
The preview properly opens in browser, `:AsciiDocPreview` and `:AsciiDocPreviewOpen` work.
`:AsciiDocPreviewNotify` or `:AsciiDocPreviewStop` are just overwritten by  `:AsciiDocPreviewOpen`. So at least the needed functionality is there, the fix probably needs some extra care.

**Comment by tigion** [comment]
The normal behavior is that the preview is started with `AsciiDocPreview` and the preview exits when leaving the Neovim buffer (with an open AsciiDoc file).

The commands `AsciiDocPreviewOpen`, `AsciiDocPreviewNotify` or `AsciiDocPreviewStop` are covered by normal use. They simply offer the option of triggering things separately.

**Comment by jirafey** [comment]
> The normal behavior is that the preview is started with `AsciiDocPreview` (starts the preview node server and opens the the preview url in the web browser) and the preview exits (stops the preview node server)when leaving the Neovim buffer (with an open AsciiDoc file).
> 
> The commands `AsciiDocPreviewOpen` (only opens the the preview url in the web browser), `AsciiDocPreviewNotify` (tells the preview to refresh) or `AsciiDocPreviewStop` (stops the preview node server) are covered by normal use. They simply offer the option of triggering things separately.

so it stops when you exit the file.
But stop does not stop the preview node server
And I'm not sure about the notify one. I'll record a video later today, maybe it will be easier for you to understand, what is going on.

**Comment by tigion** [comment]
You are right. The preview server is currently terminated when vim is closed (Event: `VimLeavePre`).

**Comment by jirafey** [comment]
> You are right. The preview server is currently terminated when vim is closed (Event: `VimLeavePre`). `:AsciiDocPreviewStop` stops the preview server manually.

the issue is that it was not being closed when `:AsciiDocPreviewStop` was used or any other option was just running `:AsciiDocPreviewOpen` (open the server node preview in new tab)

**Comment by tigion** [comment]
You are too fast. I edited my text. Can you please open a new issue for this problem.

**Comment by jirafey** [comment]
> You are too fast. I edited my text. Can you please open a new issue for this problem.
