### ISSUE TITLE
It works on WSL for me

### ISSUE THREAD

**Issue by WattsUp** [tigion/nvim-asciidoc-preview#8]
Not an issue per se, but the readme had a ❓  and I just installed it and it works on WSL2.

After launching :AsciiDocPreview it opened my web browser with the current file rendered.

If there is anything else I should test before updating the readme to ✅ ?

**Comment by tigion** [comment]
Thanks for the feedback.

I have not yet been able to test it under Windows with WSL. I will change the README file.
