### ISSUE TITLE
Neovim freezes when browser was not already running

### ISSUE THREAD

**Issue by VANN-Universal** [tigion/nvim-asciidoc-preview#9]
When I open AsciiDocPreview with my browser (Firefox) already running, everything works as expected. However, when no instance of Firefox is already running and a new window is opened by AsciiDocPreview, Neovim visually freezes after a few seconds. After closing Firefox, Neovim unfreezes.

`:checkhealth asciidoc-preview`:

```
asciidoc-preview: require("asciidoc-preview.health").check()

nvim-asciidoc-preview
- OK macOS (Linux) supported
- OK node installed
- OK npm installed
- OK curl installed
- OK Plugin directory is writable
- OK Log directory is writable
- OK Cache directory is writable

Asciidoctor (optional)
- The following warnings or errors can be ignored
  if Asciidoctor.js (`converter = 'js'`) is used.
- OK asciidoctor installed
- OK ruby installed
- OK asciidoctor gem installed
- OK asciidoctor-diagram gem installed
```

**Comment by tigion** [comment]
Thanks for the feedback.

A short test without an active web browser automatically starts the default web browser with the preview.

Works a `gx` on an URL in neovim without a running web browser?

**Comment by VANN-Universal** [comment]
`gx` works without a running web browser.

**Comment by tigion** [comment]
Hm ... Which operating system Version and Mac (32/64bit, ARM) are you using? I wonder why `checkhealt` shows macOS with **Linux** and not Darwin.

I have tested it on an Intel (64bit) and ARM (M3) Mac and it launches the default browser with preview.

**Comment by tigion** [comment]
I have a function to identify the open command OS dependent and I think the **Linux** instead of **Darwin** is irritating here. I think I need also a `vim.fn.has('mac')` check for such situation.

```lua
function M.get_open_cmd()
  local os = vim.uv.os_uname().sysname
  if os == 'Darwin' then
    return 'open'
  elseif os == 'Linux' then
    if vim.fn.has('wsl') == 1 then
      return 'wslview'
    else
      return 'xdg-open'
    end
  end

  print('Open browser on ' .. os .. ' not yet supported')
  return ''
end

```

**Comment by VANN-Universal** [comment]
I'm on Fedora 40. No idea where that macOS in the `:checkhealth` comes from.

I don't believe that the `M.get_open_cmd()` function is the problem since I do not have any `open` commands on my system. Since Firefox opens, that function should return `xdg-open` correctly.

**Comment by tigion** [comment]
What does the following output in the command line:
- `:lua print(vim.fn.has('mac'))`
- `:lua print(vim.fn.has('linux'))`
- `:lua print(vim.uv.os_uname().sysname)`

**Comment by VANN-Universal** [comment]
- `:lua print(vim.fn.has('mac'))`: `0`
- `:lua print(vim.fn.has('linux'))`: `1`
- `:lua print(vim.uv.os_uname().sysname)`: `Linux`

**Comment by tigion** [comment]
I have fixed the wrong entry 'macOS'.

I have not yet been able to reproduce or solve your problem. 😟

**Comment by tigion** [comment]
I don't have Linux here. Could you please test the following?

Do the following commands work when the browser is closed? Does neovim freeze?
The commands execute `xdg-open https://neovim.io/` under Linux to open a website in the standard browser.

- `:lua os.execute('xdg-open https://neovim.io/')`
- `:lua io.popen('xdg-open https://neovim.io/')`

**Comment by VANN-Universal** [comment]
I installed the new version and can confirm that `:checkhealth` now shows `Linux` correctly.

With `os.execute`, neovim freezes as soon as I press Enter. With `io.popen`, it takes a moment before neovim freezes.

**Comment by VANN-Universal** [comment]
I looked for other alternatives to `os.execute` and `io.popen` and found `vim.fn.jobstart` with `{detach = true}`. I tried `:lua vim.fn.jobstart("xdg-open https://neovim.io/", {detach = true})`, my browser opened and there was no freezing.

**Comment by tigion** [comment]
Thank you, does the following also work? (`vim.system` instead of `vim.fn.jobstart`)
- `:lua vim.system({'xdg-open', 'https://neovim.io/'})`
- `:lua vim.system({'xdg-open', 'https://neovim.io/'}, { detach = true })`

**Comment by VANN-Universal** [comment]
Both commands work.

**Comment by tigion** [comment]
I pushed a new version. I hope it works now.

**Comment by VANN-Universal** [comment]
Yes, it does. Thanks for your work.
